ipc = off 
#preload = /home/daedr/Pictures/backgrounds/azur-lane/Bg_erebus_1.jpg
#wallpaper = HDMI-A-1, /home/daedr/Pictures/backgrounds/azur-lane/Bg_erebus_1.jpg

preload = /home/daedr/Pictures/backgrounds/miku/miku-konachan-367154.jpg
wallpaper = eDP-1, /home/daedr/Pictures/backgrounds/miku/miku-konachan-367154.jpg

preload = /home/daedr/Pictures/backgrounds/miku/miku-konachan-380790.jpg
wallpaper = HDMI-A-1, /home/daedr/Pictures/backgrounds/miku/miku-konachan-380790.jpg

#preload = /home/daedr/Pictures/backgrounds/lapfox/_SNDWRK-gh/greenhouse - _SNDWRK-gh - Wallpaper G.png
#wallpaper = , /home/daedr/Pictures/backgrounds/lapfox/_SNDWRK-gh/greenhouse - _SNDWRK-gh - Wallpaper G.png

#preload = /usr/share/backgrounds/Konachan.com - 191428 sakamoto.jpg
#wallpaper = eDP-1, /usr/share/backgrounds/Konachan.com - 191428 sakamoto.jpg

#preload = /usr/share/backgrounds/lapfox/edited/greenhouse1.png
#wallpaper = eDP-1,/usr/share/backgrounds/lapfox/edited/greenhouse1.png

#preload = /usr/share/backgrounds/miku/Konachan.com - 380881 aqua_eyes aqua_hair bodysuit camera earth garter hatsune_miku kelezi long_hair planet space stars thighhighs twintails vocaloid.jpg
#wallpaper = HDMI-A-1,/usr/share/backgrounds/miku/Konachan.com - 380881 aqua_eyes aqua_hair bodysuit camera earth garter hatsune_miku kelezi long_hair planet space stars thighhighs twintails vocaloid.jpg

#output * bg /usr/share/backgrounds/tiling/tiling-cats.png tile
#output * bg /usr/share/backgrounds/poolsuite/poolside-fm-poolsuite-os.png fill
#output * bg /usr/share/backgrounds/poolsuite/poolside-fm-pacific-breeze.png fill


#output * bg /usr/share/backgrounds/catppuccin/Catppuccin_Mocha_Mauve_Horizontal.png fill
