$font = Jetbrains Mono Nerd Font

general {
    hide_cursor = true
}


animations {
    enabled = false
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
		color = rgba(000000aa)
		blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 1
    inner_color = rgba(000000ff)

    outer_color = rgba(cdd6f4ff)
    check_color = rgba(a6e3a1ff)
    fail_color = rgba(f38ba8ff)

    font_color = rgba(cdd6f4ff)
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text = Magic Password??!?
    fail_text = nope...
		dots_text_format = *
    dots_spacing = 0.3
    halign = center
    valign = center
}
