$font = Jetbrains Mono Nerd Font

general {
    hide_cursor = true
}


animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(11111b55)

    outer_color = rgba(11111b55)
    check_color = rgba(11111b00)
    fail_color = rgba(11111b55)

    font_color = rgba(a6adc8ee)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Magic Password??!?
    fail_text = $PAMFAIL
    dots_spacing = 0.3
    halign = center
    valign = center
}
