[global]
overload_tap_timeout = 10000
[ids]

*

#logitech mouse
046d:c547

[main]
capslock = overload(meta, esc)
mouse2 = overload(meta, mouse2)
numlock = capslock
rightalt = toggle(game)

meta = navi
space = overloadt(navi, space, 200)
tab = overloadt(control, tab, 200)

[navi]
h = left
j = down
k = up
l = right

; = backspace
' = enter

q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 10

[navi+shift]
h = home
l = end
j = pagedown
k = pageup
; = delete

[game]
capslock = capslock
mouse2 = mouse2
numlock = numlock
rightalt = toggle(game)

meta = meta
space = space
tab = tab


