[global]
overload_tap_timeout = 10000
[ids]

*

#logitech mouse
046d:c547

[main]
capslock = overload(meta, esc)
mouse2 = overload(meta, mouse2)
numlock = capslock
rightalt = toggle(game)

s = overloadt(symbols, s, 200)
f = overloadt(navi, f, 200)

#alt
n = overloadt(alt, n, 200)
v = overloadt(alt, v, 200)

#ctrl
m = overloadt(control, m, 200)
c = overloadt(control, c, 200)

#shift
; = overloadt(shift, ;, 200)
a = overloadt(shift, a, 200)

[game]
capslock = capslock
mouse2 = mouse2 
rightalt = toggle(game)
s = s 
f = f
d = d 
n = n 
v = v
m = m 
c = c 
; = ;
a = a

[navi]
h = left
j = down
k = up
l = right

; = backspace
' = enter

[navi+shift]
h = home
l = end
j = pagedown
k = pageup
; = delete

[symbols]
[ = +
e = =
u = _
d = -
b = \
l = |
o = (
p = )

