[global]
overload_tap_timeout = 10000
[ids]

*

#logitech mouse
046d:c547

[main]
capslock = overload(meta, esc)
mouse2 = overload(meta, mouse2)
numlock = capslock


s = overloadt(symbols, s, 200)
d = overloadt(navi, d, 200)

#alt
n = overloadt(alt, n, 200)
v = overloadt(alt, v, 200)

#shift
; = overloadt(shift, ;, 200)
a = overloadt(shift, a, 200)

[navi]
h = left
j = down
k = up
l = right

; = backspace
' = enter

[navi+shift]
h = home
l = end
j = pagedown
k = pageup
; = delete

[symbols]
p = +
e = =
u = _
d = -
b = \
l = |
o = (
p = )

