library: ~/Music/Tools/Beets/musiclibrary.db
directory: ~/Music/Tools/Beets/fallback-directory

plugins:
    - copyartifacts
    - convert
    #- missing
    #- badfiles
    - inline

paths:
    default:
        #%if{$grouping,${grouping}/}
        %if{$lapfox, L/LAPFOX, $albumartistchar}/$albumartist/%if{$tinyyear,[$tinyyear] }%if{$album,$album,$title}/%if{$multidisc,${rdisc}-}%if{$track,$track.,01.} %first{$artist} - $title

asciify_paths: yes

item_fields:
    #remove leading zeroes
    rdisc:
        str(disc).lstrip('0')

    lapfox: |
        if grouping == 'LAPFOX':
            return True
    albumartistchar: |
        from unidecode import unidecode
        ascii_artist = unidecode(albumartist)
        char = ascii_artist[:1]
        if char.isdigit():
            return '0-9'
        if char.isalpha():
            return char.upper()
        return '#'

    # pip install tinytag
    multidisc: |
        from tinytag import TinyTag
        tag: TinyTag = TinyTag.get(path)
        if not tag.disc_total: return 0
        if tag.disc_total > 1: return 1
    tinyyear: |
        from tinytag import TinyTag
        tag: TinyTag = TinyTag.get(path)
        if not tag.year: return 0
        # only get first 4 characters (cuts out month/day)
        return tag.year[:4]

replace:
    '[\\/]': ' ' # slashes
    '[\x00-\x1f]': ' ' # control characters
    '^\.': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _

import:
    copy: no
    move: no
    autotag: no

copyartifacts:
    print_ignored: yes

convert:
    format: mp3
    formats:
        mp3:
            command: ffmpeg -i $source -y -acodec libmp3lame -ab 320k $dest
            extension: mp3


